#!/bin/bash

TWIGJOB_FILE=$1

# Make folders if needed
[[ -d /workspace/output/models ]] || mkdir /workspace/output/models/
[[ -d /workspace/output/bohb_logs ]] || mkdir /workspace/output/bohb_logs

# Copy TwigJob file and use that one
cp $TWIGJOB_FILE /workspace/output/models/$RUN_ID.TwigJob.yml
TWIGJOB_FILE=/workspace/output/models/$RUN_ID.TwigJob.yml

# Get Job data
ALLOW_RESUME=$(/workspace/twig_module/get_value.py --yaml_file $TWIGJOB_FILE --item allow_resume)
RUN_ID=$(/workspace/twig_module/get_value.py --yaml_file $TWIGJOB_FILE --item run_id)
OUT_FILE=/workspace/output/models/$RUN_ID.std_out
ERR_FILE=/workspace/output/models/$RUN_ID.std_err

# Validate data and IO
if [[ $ALLOW_RESUME == "False" ]]
then
    echo $ALLOW_RESUME
    if [[ -f  $OUT_FILE ]]
    then
        echo "ERROR: $OUT_FILE already exists, stopping"
        exit 1
    fi

    if [[ -d /workspace/output/models/$RUN_ID ]]
    then
        echo "ERROR: /workspace/output/models/$RUN_ID already exists, stopping"
        exit 1
    fi
elif [[ $ALLOW_RESUME -ne "True" ]]
then
    echo "ERROR: invalid value for allow_resume in TwigJob file"
    exit 1
fi

time /workspace/twig_module/twig.py --do_your_job $TWIGJOB_FILE > $OUT_FILE 2> $ERR_FILE
