version: '3.9'

services:
    twig-gnn:
        #Basic starting info
        container_name: twig-gnn
        image: nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04

        #Set up workspace
        working_dir: /workspace
        volumes:
            - ./GNN_module/:/workspace/GNN_module
            - ./CensNet_module/:/workspace/CensNet_module
            - ./NAS_module/:/workspace/NAS_module
            - ./twig_module/:/workspace/twig_module
            - ./output/:/workspace/output

        #Enable nvidia https://docs.docker.com/compose/gpu-support/
        deploy: 
            resources: 
                reservations: 
                    devices: 
                        - capabilities: [gpu]
        
        #Install TWIG
        command: bash -c "twig_module/twig-install.sh && tail -F /dev/null"
