version: '3.9'

services:
    twig-gnn:
        #Basic starting info
        container_name: twig-gnn
        image: nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04

        #Set up workspace
        working_dir: /workspace
        volumes:
            - ./data/:/workspace/data
            - ./config/:/workspace/config
            - ./GNN-module/:/workspace/GNN-module
            - ./NAS-module/:/workspace/NAS-module

        #Enable nvidia https://docs.docker.com/compose/gpu-support/
        deploy: 
            resources: 
                reservations: 
                    devices: 
                        - capabilities: [gpu]
        
        #Install TWIG
        command: bash -c "config/twig-install.sh && tail -F /dev/null"

    twig-mongo:
        #Basic starting info
        conainer_name: twig-mongo
        image: mongo/mongo:5.0.3

        #Set up workspace
        working_dir: /workspace

        ports:
            - 1234:1234

        #Install MONGO
        command: bash -c "config/mongo-install.sh && tail -F /dev/null"
