version: '3.9'

services:
    twig-gnn:
        #Basic starting info
        container_name: twig-gnn
        image: nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04

        #Set up workspace
        working_dir: /workspace
        volumes:
            - ./data/:/workspace/data
            - ./GNN-module/:/workspace/GNN-module
            - ./NAS-module/:/workspace/NAS-module
            - ./twig-module/:/workspace/twig-module

        #Enable nvidia https://docs.docker.com/compose/gpu-support/
        deploy: 
            resources: 
                reservations: 
                    devices: 
                        - capabilities: [gpu]
        
        #Install TWIG
        command: bash -c "twig-module/twig-install.sh && tail -F /dev/null"

    twig-mongo:
        #Basic starting info
        container_name: twig-mongo
        image: mongo:5.0.3

        #Set up workspace
        working_dir: /workspace

        volumes:
            - ./mongo-module/:/workspace/mongo-module

        #Install MONGO
        command: bash -c "mongo-module/mongo-start.sh && tail -F /dev/null"
